language: node_js

node_js:
  - 10.16.0

after_success:
  - npm run coverage

services:
  - postgresql

  postgres: 
  adapter: postgresql
  database: broadcaster
  username: postgres   


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run db:setup


