language: node_js

node_js:
  - 10.16.0

after_success:
  - npm run coverage

services:
  - postgresql
  

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 4512;" -U postgres


