language: node_js

node_js:
  - 10.16.0

after_success:
  - npm run coverage

services:
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres



